enum SongLibrary {
    static func songs(bpm: Int) -> [Song] {
        all.filter { $0.bpm == bpm }.sorted { $0.artist < $1.artist }
    }

    static let all: [Song] = [
        Song(id: 1, artist: "Ying Yang Twins", title: "I Yi Yi", key: 2, bpm: 94),
        Song(id: 2, artist: "2Pac", title: "How Do U Want It", key: 2, bpm: 94),
        Song(id: 3, artist: "Too Short", title: "Couldn't Be a Better Player", key: 2, bpm: 94),
        Song(id: 4, artist: "Snoop Dogg", title: "What's My Name", key: 10, bpm: 94),
        Song(id: 5, artist: "Notorious BIG", title: "Hypnotize", key: 9, bpm: 94),
        Song(id: 6, artist: "Nas", title: "If I Ruled the World", key: 2, bpm: 94),
        Song(id: 7, artist: "Mobb Deep", title: "Shook Ones Part 2", key: 3, bpm: 94),
        Song(id: 8, artist: "Ludacris", title: "Southern Hospitality", key: 10, bpm: 94),
        Song(id: 9, artist: "Lil Wayne", title: "Shine", key: 6, bpm: 94),
        Song(id: 10, artist: "Kane and Abel", title: "Show Dat Work", key: 8, bpm: 94),
        Song(id: 11, artist: "Juvenile", title: "Back Dat Ass Up", key: 7, bpm: 94),
        Song(id: 12, artist: "J-Kwon", title: "Tipsy", key: 4, bpm: 94),
        Song(id: 13, artist: "Dr Dre", title: "The Next Episode", key: 2, bpm: 94),
        Song(id: 14, artist: "David Banner", title: "Play", key: 5, bpm: 94),
        Song(id: 15, artist: "Clipse", title: "Grindin'", key: 4, bpm: 94),
        Song(id: 16, artist: "Ali", title: "Breathe In, Breathe Out", key: 8, bpm: 94),
        Song(id: 17, artist: "C-Murder", title: "Down for my Ns", key: 1, bpm: 94),
        Song(id: 18, artist: "Boo & Gotti", title: "Ain't It Man", key: 4, bpm: 94),
        Song(id: 19, artist: "T.I.", title: "Why U Wanna", key: 8, bpm: 94),
        Song(id: 20, artist: "50 Cent", title: "In Da Club", key: 6, bpm: 94),
        Song(id: 21, artist: "Beyonce", title: "Single Ladies", key: 4, bpm: 94),
        Song(id: 22, artist: "50 Cent", title: "I Get It In", key: 12, bpm: 94),
        Song(id: 23, artist: "Dr. Dre", title: "G Thang", key: 11, bpm: 94),
        Song(id: 24, artist: "Lil Mo", title: "Superwoman Remix", key: 12, bpm: 94),
        Song(id: 25, artist: "Fabolous", title: "Can't Deny It", key: 4, bpm: 94),
        Song(id: 26, artist: "Masta Ace", title: "Born to Roll", key: 4, bpm: 94),
        Song(id: 29, artist: "Ludacris", title: "Ho", key: 8, bpm: 94),
        Song(id: 30, artist: "Snoop Dogg", title: "Deep Cover", key: 4, bpm: 94),
        Song(id: 31, artist: "Snoop Dogg", title: "Drop It Like Its Hot", key: 9, bpm: 94),
        Song(id: 32, artist: "Dr Dre", title: "Dre Day", key: 1, bpm: 94),
        Song(id: 34, artist: "Juvenile", title: "Ha", key: 5, bpm: 94),
        Song(id: 35, artist: "Silk the Shocker", title: "Aint My Fault Part 2", key: 4, bpm: 94),
        Song(id: 36, artist: "Nas", title: "Street Dreams", key: 6, bpm: 94),
        Song(id: 37, artist: "Lil Wayne", title: "I Need a Hot Girl", key: 6, bpm: 94),
        Song(id: 38, artist: "Paul Cameron", title: "Brown Beat", key: 8, bpm: 94),
        Song(id: 40, artist: "Sean Paul", title: "Baby Boy", key: 12, bpm: 94),
        Song(id: 41, artist: "Pastor Troy", title: "Are We Cuttin", key: 8, bpm: 94),
        Song(id: 42, artist: "MOP", title: "Ante Up", key: 4, bpm: 94),
        Song(id: 43, artist: "Total", title: "What About Us Remix", key: 3, bpm: 94),
        Song(id: 44, artist: "Nelly", title: "Shake Ya Tailfeather", key: 11, bpm: 94),
        Song(id: 46, artist: "Ludacris", title: "Move B*tch", key: 11, bpm: 94),
        Song(id: 47, artist: "Mystikal", title: "Been So Long", key: 11, bpm: 94),
        Song(id: 48, artist: "Cheeky Blakk", title: "B*tch Get Off Me", key: 1, bpm: 94),
        Song(id: 49, artist: "Chingy", title: "Right Thurr", key: 2, bpm: 94),
        Song(id: 50, artist: "Chris Brown", title: "Wall 2 Wall", key: 4, bpm: 94),
        Song(id: 51, artist: "Young Buck", title: "Shorty Wanna Ride", key: 4, bpm: 94),
        Song(id: 52, artist: "Juvenile", title: "In My Life", key: 9, bpm: 94),
        Song(id: 54, artist: "Juvenile", title: "From Her Mama", key: 6, bpm: 94),
        Song(id: 55, artist: "Big Tymers", title: "Number One Stunna", key: 1, bpm: 94),
        Song(id: 56, artist: "Big Tymers", title: "Get Your Roll On", key: 1, bpm: 94),
        Song(id: 57, artist: "LL Cool J", title: "Doin It", key: 4, bpm: 94),
        Song(id: 58, artist: "Jim Jones", title: "We Fly High", key: 1, bpm: 94),
        Song(id: 59, artist: "Kia Shine", title: "Krispy", key: 8, bpm: 94),
        Song(id: 60, artist: "Vockah Redu", title: "Roll Call", key: 10, bpm: 94),
        Song(id: 61, artist: "Quint Black", title: "Shake Dem Haters Off", key: 12, bpm: 94),
        Song(id: 62, artist: "Traxster", title: "Freak Hoes", key: 2, bpm: 84),
        Song(id: 63, artist: "Lil Wayne", title: "Bring it Back", key: 6, bpm: 84),
        Song(id: 64, artist: "Youngbloodz", title: "Presidential", key: 6, bpm: 84),
        Song(id: 65, artist: "Lil Wayne", title: "Go DJ", key: 1, bpm: 84),
        Song(id: 66, artist: "Total", title: "What About Us Remix", key: 1, bpm: 84),
        Song(id: 67, artist: "Master P", title: "I'm a Ho", key: 1, bpm: 84),
        Song(id: 68, artist: "Jay-Z", title: "Dirt Off Your Shoulder", key: 3, bpm: 84),
        Song(id: 69, artist: "Lil Boosie", title: "Wipe Me Down Remix", key: 4, bpm: 84),
        Song(id: 70, artist: "Snoop Dogg", title: "Woof", key: 11, bpm: 84),
        Song(id: 72, artist: "Kelis", title: "Bossy", key: 2, bpm: 84),
        Song(id: 73, artist: "Chris Brown", title: "Get Like Me", key: 1, bpm: 84),
        Song(id: 74, artist: "Ludacris", title: "Get Back", key: 3, bpm: 84),
        Song(id: 75, artist: "Lil Wayne", title: "Stuntin' Like My Daddy", key: 11, bpm: 84),
        Song(id: 76, artist: "Super Duck Breaks", title: "Beak This", key: 10, bpm: 84),
        Song(id: 77, artist: "Trillville", title: "Some Cut", key: 9, bpm: 84),
        Song(id: 78, artist: "Nelly", title: "E.I.", key: 1, bpm: 84),
        Song(id: 79, artist: "504 Boys", title: "Wobble Wobble", key: 1, bpm: 84),
        Song(id: 80, artist: "T.I.", title: "Big Things Poppin'", key: 5, bpm: 84),
        Song(id: 81, artist: "P$C", title: "I'm a King", key: 4, bpm: 84),
        Song(id: 82, artist: "Juvenile", title: "Set It Off", key: 4, bpm: 84),
        Song(id: 83, artist: "T.I.", title: "24's", key: 11, bpm: 84),
        Song(id: 84, artist: "54th Platoon", title: "Holdin' It Down", key: 12, bpm: 84),
        Song(id: 85, artist: "Lil Scrappy", title: "No Problem", key: 5, bpm: 84),
        Song(id: 86, artist: "Bubba Sparxxx", title: "Ugly", key: 11, bpm: 94),
        Song(id: 87, artist: "Nas", title: "Oochie Wally", key: 11, bpm: 94),
        Song(id: 88, artist: "Quint Black", title: "Shake Dem Haters Remix", key: 12, bpm: 94),
        Song(id: 89, artist: "Da Sha Ra", title: "Bootin' Up", key: 1, bpm: 94),
        Song(id: 90, artist: "Usher", title: "You Make Me Wanna Remix", key: 5, bpm: 84),
        Song(id: 91, artist: "Three 6 Mafia", title: "You Scared Part 2", key: 1, bpm: 84),
        Song(id: 92, artist: "Nelly", title: "Country Grammar", key: 6, bpm: 84),
        Song(id: 93, artist: "Webbie", title: "Bad B*tch", key: 8, bpm: 84),
        Song(id: 94, artist: "T.I.", title: "Top Back", key: 1, bpm: 84),
        Song(id: 95, artist: "David Banner", title: "Shawty Say", key: 6, bpm: 84),
        Song(id: 96, artist: "Lil Keke", title: "Southside", key: 12, bpm: 84),
        Song(id: 97, artist: "Kingpin Skinny Pimp", title: "TVs Remix", key: 9, bpm: 84),
        Song(id: 98, artist: "Three 6 Mafia", title: "Ask & Get It", key: 4, bpm: 84),
        Song(id: 99, artist: "Three 6 Mafia", title: "Who Run It", key: 6, bpm: 84),
        Song(id: 100, artist: "Jay-Z", title: "Hey Papi", key: 12, bpm: 84),
        Song(id: 101, artist: "Project Pat", title: "Ooh Nuttin", key: 2, bpm: 84),
        Song(id: 102, artist: "Lil Troy", title: "We Gon Lean", key: 2, bpm: 84),
        Song(id: 103, artist: "Youngbloodz", title: "Datz Me", key: 6, bpm: 84),
        Song(id: 104, artist: "Project Pat", title: "Dont Save Her", key: 3, bpm: 84),
        Song(id: 105, artist: "E-40", title: "Rep Yo City", key: 1, bpm: 84),
        Song(id: 106, artist: "Lil Jon", title: "I Dont Give a What", key: 8, bpm: 84),
        Song(id: 107, artist: "Rich Boy", title: "Throw Some Ds", key: 4, bpm: 84),
        Song(id: 108, artist: "Project Pat", title: "Gel and Weave", key: 5, bpm: 84),
        Song(id: 109, artist: "Wacko Skip & Juvenile", title: "Nolia Clap", key: 2, bpm: 84),
        Song(id: 110, artist: "Lil Wayne", title: "Fireman", key: 6, bpm: 84),
        Song(id: 111, artist: "Yung Joc", title: "It's Goin Down", key: 1, bpm: 84),
        Song(id: 112, artist: "Ludacris", title: "D@mn", key: 9, bpm: 84),
        Song(id: 113, artist: "Magic", title: "I Smoke I Drank Remix", key: 9, bpm: 84),
        Song(id: 114, artist: "DJ KaySlay", title: "Who Gives A ...", key: 4, bpm: 84),
        Song(id: 115, artist: "Nelly", title: "Air Force Ones", key: 10, bpm: 84),
        Song(id: 116, artist: "Lil Jon", title: "Snap Yo Fingers", key: 1, bpm: 84),
        Song(id: 117, artist: "Nelly", title: "Grillz", key: 11, bpm: 84),
        Song(id: 118, artist: "Cam'Ron", title: "Down and Out", key: 4, bpm: 84),
        Song(id: 119, artist: "Busta Rhymes", title: "Break Yo Neck", key: 8, bpm: 84),
        Song(id: 120, artist: "Project Pat", title: "Back Clap Remix", key: 12, bpm: 84),
        Song(id: 121, artist: "Three 6 Mafia", title: "Ridin Spinners", key: 8, bpm: 84),
        Song(id: 122, artist: "Ludacris", title: "D@mn Remix", key: 9, bpm: 84),
        Song(id: 123, artist: "Too Short", title: "Shake That Monkey", key: 8, bpm: 102),
        Song(id: 124, artist: "Juelz Santana", title: "There It Go", key: 6, bpm: 102),
        Song(id: 125, artist: "LL Cool J", title: "Headsprung", key: 1, bpm: 102),
        Song(id: 126, artist: "Sean Paul", title: "Get Busy", key: 2, bpm: 102),
        Song(id: 127, artist: "Choppa", title: "Choppa Style", key: 2, bpm: 102),
        Song(id: 128, artist: "Master P", title: "Rock It", key: 1, bpm: 102),
        Song(id: 129, artist: "Too Short", title: "Blow the Whistle", key: 5, bpm: 102),
        Song(id: 130, artist: "Too Short", title: "Burn Rubber", key: 5, bpm: 102),
        Song(id: 131, artist: "Lil Jon", title: "Get Low", key: 5, bpm: 102),
        Song(id: 132, artist: "Master P", title: "Them Jeans", key: 5, bpm: 102),
        Song(id: 133, artist: "Da Sha Ra", title: "Bootin' Up", key: 2, bpm: 102),
        Song(id: 134, artist: "Loon", title: "How U Want That", key: 1, bpm: 102),
        Song(id: 135, artist: "Khia", title: "My Neck, My Back", key: 8, bpm: 102),
        Song(id: 136, artist: "Ying Yang Twins", title: "Salt Shaker", key: 2, bpm: 102),
        Song(id: 137, artist: "Usher", title: "Yeah", key: 6, bpm: 102),
        Song(id: 138, artist: "T.I.", title: "I'm Serious Remix", key: 9, bpm: 102),
        Song(id: 139, artist: "Busta Rhymes", title: "Light Your A$$ On Fire", key: 12, bpm: 102),
        Song(id: 140, artist: "Missy Elliott", title: "Work It", key: 5, bpm: 102),
        Song(id: 141, artist: "E-40", title: "Tell Me When To Go", key: 9, bpm: 102),
        Song(id: 142, artist: "The Showboys", title: "Drag Rap", key: 9, bpm: 94),
        Song(id: 143, artist: "Young Gunz", title: "Can't Stop Won't Stop", key: 1, bpm: 102),
        Song(id: 144, artist: "Petey Pablo", title: "Freek a Leek", key: 1, bpm: 102),
        Song(id: 145, artist: "Ludacris", title: "Stand Up", key: 3, bpm: 102),
        Song(id: 146, artist: "Cheeky Blakk", title: "B*tch Get Off Me", key: 1, bpm: 102),
        Song(id: 147, artist: "Jay-Z", title: "Just Wanna Luv U", key: 4, bpm: 102),
        Song(id: 148, artist: "Silky Slim", title: "Sista Sista", key: 6, bpm: 102),
        Song(id: 149, artist: "Ludacris", title: "Area Codes", key: 8, bpm: 102),
        Song(id: 150, artist: "Chris Brown", title: "Run It", key: 2, bpm: 102),
        Song(id: 151, artist: "Ying Yang Twins", title: "Whistle While You Twerk", key: 2, bpm: 102),
        Song(id: 152, artist: "5th Ward Webbie", title: "On Da Wall", key: 11, bpm: 102),
        Song(id: 153, artist: "5th Ward Webbie", title: "Toot It Up", key: 6, bpm: 102),
        Song(id: 154, artist: "The Pack", title: "Vans", key: 2, bpm: 102),
        Song(id: 155, artist: "Montell Jordan", title: "This Is How We Do It", key: 4, bpm: 102),
        Song(id: 156, artist: "Ying Yang Twins", title: "Whisper", key: 3, bpm: 102),
        Song(id: 157, artist: "FRESH", title: "Cake Boy", key: 2, bpm: 84),
        Song(id: 158, artist: "Bloodclot Breaks", title: "Kuttin Like a Maniac", key: 2, bpm: 84),
        Song(id: 159, artist: "Super Seal", title: "Side B Break", key: 8, bpm: 84),
        Song(id: 160, artist: "Fat Joe", title: "Make It Rain", key: 11, bpm: 84),
        Song(id: 161, artist: "Crime Mobb", title: "Rock Ya Hips", key: 1, bpm: 84),
        Song(id: 162, artist: "Crime Mobb", title: "Stilettos", key: 1, bpm: 84),
        Song(id: 163, artist: "DJ DMD", title: "25 Lighters", key: 2, bpm: 84),
        Song(id: 164, artist: "Ludacris", title: "Catch Up", key: 11, bpm: 84),
        Song(id: 165, artist: "8-Ball & MJG", title: "Pimp Hard", key: 12, bpm: 84),
        Song(id: 166, artist: "Three 6 Mafia", title: "Chickenheads", key: 1, bpm: 84),
        Song(id: 167, artist: "Bravehearts", title: "Quick to Back Down", key: 4, bpm: 84),
        Song(id: 168, artist: "G-Unit", title: "Wanna Get to Know You", key: 5, bpm: 84),
        Song(id: 169, artist: "Gangsta Boo", title: "Where Dem Dollas At", key: 2, bpm: 84),
        Song(id: 170, artist: "Tango", title: "Wobble & Shake It", key: 9, bpm: 84),
        Song(id: 172, artist: "Webbie", title: "How U Ridin'", key: 6, bpm: 84),
        Song(id: 173, artist: "Jim Jones", title: "Weatherman", key: 3, bpm: 84),
        Song(id: 174, artist: "Ludacris", title: "Act a Fool", key: 9, bpm: 84),
        Song(id: 175, artist: "Mobb Deep", title: "Get It Twisted", key: 1, bpm: 102),
        Song(id: 176, artist: "Saweetie", title: "My Type Remix", key: 6, bpm: 102),
        Song(id: 177, artist: "Ying Yang Twins", title: "Get It Girl", key: 1, bpm: 102),
        Song(id: 178, artist: "Big Freedia", title: "A$$ Everywhere", key: 4, bpm: 102),
        Song(id: 179, artist: "Drake", title: "Nice for What", key: 4, bpm: 94),
        Song(id: 180, artist: "Joe Budden", title: "Pump It Up", key: 3, bpm: 102),
        Song(id: 181, artist: "DJ Felli Fell", title: "Get Buck in Here", key: 1, bpm: 102),
        Song(id: 182, artist: "B.G.", title: "Bling Bling", key: 9, bpm: 102),
        Song(id: 185, artist: "Busta Rhymes", title: "Fire It Up", key: 8, bpm: 102),
        Song(id: 186, artist: "Too Short", title: "Keep Bouncing", key: 10, bpm: 102),
        Song(id: 187, artist: "Notorious BIG", title: "Nasty Girl", key: 12, bpm: 102),
        Song(id: 188, artist: "Saweetie", title: "Up Now", key: 2, bpm: 102),
        Song(id: 189, artist: "Missy Elliott", title: "Ching a Ling", key: 4, bpm: 102),
        Song(id: 190, artist: "Kilo", title: "Who Dat Call tha Police", key: 1, bpm: 102),
        Song(id: 191, artist: "Kilo", title: "Get In Line", key: 3, bpm: 102),
        Song(id: 192, artist: "Mobb Deep", title: "Real Gangstaz", key: 9, bpm: 102),
        Song(id: 193, artist: "Doug E Fresh", title: "The Show", key: 4, bpm: 102),
        Song(id: 194, artist: "50 Cent", title: "Candy Shop", key: 6, bpm: 102),
        Song(id: 200, artist: "FM", title: "Gimme What You Got", key: 2, bpm: 102),
        Song(id: 207, artist: "Master P", title: "Ghetto D", key: 5, bpm: 102),
        Song(id: 208, artist: "Mystikal", title: "Shake Ya Ass", key: 1, bpm: 102),
        Song(id: 209, artist: "Naughty by Nature", title: "O.P.P.", key: 6, bpm: 102),
        Song(id: 210, artist: "Onyx", title: "Slam", key: 3, bpm: 102),
        Song(id: 213, artist: "R Kelly", title: "Playas Only", key: 1, bpm: 102),
        Song(id: 216, artist: "Skee Lo", title: "I Wish", key: 1, bpm: 102),
        Song(id: 217, artist: "Swizz Beats", title: "Money In the Bank", key: 2, bpm: 102),
        Song(id: 218, artist: "The Game", title: "How We Do", key: 4, bpm: 102),
        Song(id: 224, artist: "The Game", title: "Hate It or Love It", key: 12, bpm: 102),
        Song(id: 227, artist: "Ying Yang Twins", title: "Twurkulator Part 2", key: 7, bpm: 102),
        Song(id: 230, artist: "Next", title: "Too Close", key: 11, bpm: 102),
        Song(id: 236, artist: "Ying Yang Twins", title: "Twerking in the Mirror", key: 2, bpm: 102),
        Song(id: 242, artist: "Beyonce", title: "Naughty Girl", key: 10, bpm: 102),
        Song(id: 243, artist: "Slim", title: "So Fly Remix", key: 7, bpm: 94),
        Song(id: 260, artist: "Amerie", title: "1 Thing", key: 5, bpm: 102),
        Song(id: 263, artist: "Youngbloodz", title: "Cadillac Pimpin", key: 2, bpm: 94),
        Song(id: 270, artist: "Junior MAFIA", title: "Get Money", key: 5, bpm: 94),
        Song(id: 273, artist: "Rihanna feat Young Jeezy", title: "Hard", key: 5, bpm: 94),
        Song(id: 275, artist: "Eve", title: "Tamborine Remix", key: 5, bpm: 102),
        Song(id: 276, artist: "Funkdoobiest", title: "Bow Wow Wow Remix", key: 11, bpm: 102),
        Song(id: 278, artist: "Bhad Barbie", title: "Bestie", key: 4, bpm: 102),
        Song(id: 280, artist: "DMX", title: "Stop Bein Greedy", key: 5, bpm: 102),
        Song(id: 283, artist: "Baby", title: "Do That", key: 1, bpm: 102),
        Song(id: 284, artist: "Hot Boys", title: "I Got That Fire", key: 4, bpm: 102),
        Song(id: 285, artist: "Juelz Santana", title: "Hey Ma", key: 6, bpm: 84),
        Song(id: 286, artist: "Hurricane Chris", title: "Hand Clap", key: 11, bpm: 84),
        Song(id: 287, artist: "Eightball", title: "Lay It Down", key: 4, bpm: 84),
        Song(id: 289, artist: "Outkast", title: "So Fresh So Clean", key: 5, bpm: 84),
        Song(id: 290, artist: "MoneyBagg Yo", title: "Wockesha Remix", key: 8, bpm: 84),
        Song(id: 291, artist: "Master P", title: "Make Em Say Uhhh", key: 4, bpm: 84),
        Song(id: 292, artist: "Funk Shid Up", title: "Sucka Stepped Up", key: 6, bpm: 84),
        Song(id: 294, artist: "Missy Elliott", title: "Hot Boyz", key: 11, bpm: 84),
        Song(id: 296, artist: "T-Pain", title: "Got Money", key: 9, bpm: 84),
        Song(id: 298, artist: "Audio Two", title: "Top Billin", key: 4, bpm: 94),
        Song(id: 299, artist: "50 Cent", title: "Get Up", key: 10, bpm: 94),
        Song(id: 301, artist: "City Girls", title: "P&ssy Talk", key: 1, bpm: 102),
        Song(id: 303, artist: "Cam'Ron", title: "Oh Boy", key: 1, bpm: 84),
        Song(id: 304, artist: "T.I.", title: "Front Back", key: 2, bpm: 84),
        Song(id: 306, artist: "Lord Tariq & Peter Gunz", title: "Deva Vu Uptown Baby", key: 7, bpm: 102),
        Song(id: 307, artist: "NORE", title: "Nothin", key: 8, bpm: 102),
        Song(id: 308, artist: "Paperboy", title: "Ditty", key: 7, bpm: 102),
        Song(id: 309, artist: "The Game", title: "Game's Pain", key: 6, bpm: 102),
        Song(id: 310, artist: "DMX", title: "Up In Here", key: 2, bpm: 102),
        Song(id: 311, artist: "Outkast", title: "Rosa Parks", key: 1, bpm: 102),
        Song(id: 312, artist: "Baby D", title: "F That Side", key: 2, bpm: 102),
        Song(id: 313, artist: "Lil Goldie", title: "Act a Donkey", key: 12, bpm: 102),
        Song(id: 314, artist: "5th Ward Webbie", title: "Toot it Up Remix", key: 6, bpm: 102),
        Song(id: 316, artist: "Jay-Z", title: "Excuse Me Miss Remix", key: 4, bpm: 102),
        Song(id: 317, artist: "Tracey Lee", title: "The Theme", key: 1, bpm: 102),
        Song(id: 318, artist: "Pras", title: "Ghetto Superstar", key: 4, bpm: 102),
        Song(id: 319, artist: "Lauryn Hill", title: "That Thing", key: 2, bpm: 102),
        Song(id: 320, artist: "Notorious BIG", title: "Goin Back to Cali", key: 3, bpm: 102),
        Song(id: 321, artist: "DJ Khaled", title: "Holla At Me", key: 4, bpm: 102),
        Song(id: 322, artist: "Megan thee Stallion", title: "Hot Girl Summer", key: 3, bpm: 102),
        Song(id: 323, artist: "G-Unit", title: "Ryder Part 2", key: 4, bpm: 102),
        Song(id: 324, artist: "Murphy Lee", title: "What the Hook Gon Be", key: 4, bpm: 102),
        Song(id: 325, artist: "Puff Daddy", title: "Can't Hold Me Down", key: 4, bpm: 102),
        Song(id: 326, artist: "DJ Jazzy Jeff", title: "Brand New Funk", key: 4, bpm: 102),
        Song(id: 329, artist: "Fat Joe", title: "Lean Back Remix", key: 8, bpm: 102),
        Song(id: 330, artist: "Wyclef Jean", title: "We Trying to Stay Alive", key: 4, bpm: 102),
        Song(id: 331, artist: "G Dep", title: "Special Delivery", key: 2, bpm: 102),
        Song(id: 332, artist: "Offset & Metro Boomin", title: "Ric Flair Drip", key: 2, bpm: 102),
        Song(id: 333, artist: "Bubba Sparxx", title: "Ms New Booty", key: 1, bpm: 102),
        Song(id: 334, artist: "E-40", title: "White Girl", key: 2, bpm: 102),
        Song(id: 335, artist: "Notorious BIG", title: "Dead Wrong", key: 1, bpm: 84),
        Song(id: 336, artist: "DJ UNK", title: "Walk It Out", key: 9, bpm: 84),
        Song(id: 337, artist: "Lil Boosie", title: "Supafly", key: 11, bpm: 84),
        Song(id: 338, artist: "Jamie Foxx", title: "Blame It", key: 3, bpm: 84),
        Song(id: 339, artist: "Gucci Mane", title: "Go Head", key: 1, bpm: 84),
        Song(id: 340, artist: "Durrough", title: "Walk that Walk", key: 9, bpm: 84),
        Song(id: 343, artist: "Bun B", title: "That's Gangsta", key: 9, bpm: 84),
        Song(id: 344, artist: "Cookie Ekawaii", title: "If I Back It Up", key: 1, bpm: 84),
        Song(id: 346, artist: "Young Jeezy", title: "Get Some Money", key: 2, bpm: 84),
        Song(id: 347, artist: "Lil Boosie", title: "Zoom", key: 4, bpm: 84),
        Song(id: 348, artist: "MIMS", title: "This is Why I'm Hot", key: 12, bpm: 84),
        Song(id: 349, artist: "Nappy Roots", title: "Aww-Naww", key: 1, bpm: 84),
        Song(id: 350, artist: "Webbie", title: "Like That", key: 12, bpm: 84),
        Song(id: 351, artist: "Young Jeezy", title: "Black Tee", key: 6, bpm: 84),
        Song(id: 352, artist: "UGK", title: "Let Me See It", key: 4, bpm: 84),
        Song(id: 354, artist: "Webbie", title: "Gimme That", key: 1, bpm: 84),
        Song(id: 355, artist: "Lil Boosie", title: "Adios", key: 11, bpm: 84),
        Song(id: 356, artist: "Gucci Mane", title: "Wasted", key: 2, bpm: 84),
        Song(id: 357, artist: "D4L", title: "Laffy Taffy", key: 1, bpm: 84),
        Song(id: 358, artist: "T.I.", title: "Rubber Band Man", key: 1, bpm: 84),
        Song(id: 359, artist: "Rocko", title: "Tomorrow", key: 6, bpm: 84),
        Song(id: 360, artist: "Concrete Boys", title: "Crank Dat Roadrunner", key: 2, bpm: 84),
        Song(id: 361, artist: "Project Pat", title: "Good Googly Moogly", key: 1, bpm: 84),
        Song(id: 362, artist: "T.I.", title: "Be Easy", key: 4, bpm: 84),
        Song(id: 363, artist: "DJ UNK", title: "2 Step", key: 1, bpm: 84),
        Song(id: 364, artist: "Petey Pablo", title: "Raise Up", key: 2, bpm: 84),
        Song(id: 365, artist: "Gz", title: "Do the Stanky Leg", key: 5, bpm: 84),
        Song(id: 367, artist: "Cali Swag District", title: "Teach Me How to Dougie", key: 10, bpm: 84),
        Song(id: 368, artist: "Trillville", title: "Neva Eva", key: 2, bpm: 84),
        Song(id: 370, artist: "Kilo", title: "Tick Tock Bass Remix", key: 1, bpm: 84),
        Song(id: 372, artist: "Eminem", title: "Stan", key: 6, bpm: 84),
        Song(id: 373, artist: "Billy Wes", title: "Shake That Jelly", key: 2, bpm: 84),
        Song(id: 375, artist: "The Game", title: "Big Dreams", key: 1, bpm: 84),
        Song(id: 376, artist: "T.I.", title: "ASAP", key: 2, bpm: 84),
        Song(id: 377, artist: "TELA", title: "Got Pimpin", key: 10, bpm: 84),
        Song(id: 378, artist: "Shawty Lo", title: "Supplier", key: 9, bpm: 84),
        Song(id: 382, artist: "Juvenile", title: "Rodeo", key: 11, bpm: 84),
        Song(id: 383, artist: "JR Writer", title: "Grill Em", key: 11, bpm: 84),
        Song(id: 388, artist: "Yo Gotti", title: "King Sh*t", key: 4, bpm: 84),
        Song(id: 390, artist: "ASAP", title: "Rocky Cocky", key: 2, bpm: 84),
        Song(id: 391, artist: "Yung LA", title: "Ain't I", key: 4, bpm: 84),
        Song(id: 392, artist: "Youngbloodz", title: "85", key: 4, bpm: 84),
        Song(id: 396, artist: "The Game", title: "Put You In the Game", key: 6, bpm: 84),
        Song(id: 398, artist: "Pitbull", title: "Dem Miami Boys", key: 2, bpm: 84),
        Song(id: 400, artist: "Notorious BIG", title: "Big Poppa", key: 8, bpm: 84),
        Song(id: 401, artist: "Youngbloodz", title: "Presidential Remix", key: 1, bpm: 84),
        Song(id: 402, artist: "T.I.", title: "You Know What It Is", key: 9, bpm: 84),
        Song(id: 403, artist: "Kingpin Skinny Pimp", title: "TVs", key: 9, bpm: 84),
        Song(id: 404, artist: "Black Rob", title: "Whoa", key: 11, bpm: 84),
        Song(id: 406, artist: "Beastie Boys", title: "Posse In Effect", key: 1, bpm: 84),
        Song(id: 407, artist: "Three 6 Mafia", title: "Side 2 Side", key: 10, bpm: 84),
        Song(id: 408, artist: "Mystikal", title: "Here I Go", key: 3, bpm: 84),
        Song(id: 410, artist: "Luniz", title: "I Got 5 On It", key: 4, bpm: 84),
        Song(id: 411, artist: "Dogg Pound", title: "New York New York", key: 11, bpm: 84),
        Song(id: 414, artist: "Lil Wayne", title: "The Block is Hot", key: 2, bpm: 84),
        Song(id: 416, artist: "Cassidy", title: "Drink & My 2 Step", key: 8, bpm: 84),
        Song(id: 417, artist: "Paul Wall", title: "Bizzy Body", key: 2, bpm: 84),
        Song(id: 418, artist: "Webbie", title: "Independent", key: 2, bpm: 84),
        Song(id: 419, artist: "Field Mob", title: "Sick of Being Lonely", key: 1, bpm: 84),
        Song(id: 420, artist: "Above the Law", title: "Black Superman", key: 8, bpm: 84),
        Song(id: 421, artist: "Ron Browz", title: "Jumpin Out the Window", key: 1, bpm: 84),
        Song(id: 422, artist: "DJ Khaled", title: "Out Here Grinding", key: 5, bpm: 84),
        Song(id: 423, artist: "Big Tymers", title: "Big Ballin", key: 12, bpm: 84),
        Song(id: 425, artist: "Birdman", title: "What Happened to That Boy", key: 10, bpm: 94),
        Song(id: 426, artist: "Snoop Dogg", title: "Drop It Like Its Hot Remix", key: 5, bpm: 94),
        Song(id: 427, artist: "Nelly", title: "E.I. Tipdrill Remix", key: 2, bpm: 94),
        Song(id: 428, artist: "Junior MAFIA", title: "Players Anthem Remix", key: 11, bpm: 94),
        Song(id: 431, artist: "T.I.", title: "Get Loose", key: 2, bpm: 94),
        Song(id: 432, artist: "Jermaine Dupri", title: "Welcome to Atlanta ATL Remix", key: 1, bpm: 94),
        Song(id: 435, artist: "Megan thee Stallion", title: "Girls In The Hood", key: 11, bpm: 94),
        Song(id: 436, artist: "Mike Jones", title: "Drop & Gimme 50", key: 9, bpm: 94),
        Song(id: 437, artist: "Durrough", title: "Ice Cream Paint Job", key: 12, bpm: 94),
        Song(id: 438, artist: "Rihanna", title: "Birthday Cake Remix", key: 2, bpm: 84),
        Song(id: 439, artist: "Future", title: "Stick Talk", key: 7, bpm: 84),
        Song(id: 440, artist: "Drake", title: "First Person Shooter", key: 9, bpm: 84),
        Song(id: 441, artist: "Master P", title: "Weed & Money", key: 2, bpm: 84),
        Song(id: 442, artist: "Drake", title: "Rich Flex", key: 8, bpm: 84),
        Song(id: 443, artist: "Playboi Carti", title: "Milli Rock", key: 10, bpm: 84),
        Song(id: 444, artist: "Three 6 Mafia", title: "Hard Out Here", key: 9, bpm: 84),
        Song(id: 445, artist: "Gunna", title: "Pushin P", key: 1, bpm: 84),
        Song(id: 446, artist: "Travis Scott & Drake", title: "SICKO MODE", key: 3, bpm: 84),
        Song(id: 447, artist: "Whodini", title: "I'm a Ho", key: 1, bpm: 84),
        Song(id: 448, artist: "Drake", title: "Girls Want Girls", key: 5, bpm: 84),
        Song(id: 449, artist: "2 Chainz & Lil Wayne", title: "Big Diamonds", key: 3, bpm: 84),
        Song(id: 450, artist: "Three 6 Mafia", title: "Let's Run a Train", key: 2, bpm: 84),
        Song(id: 451, artist: "Drake", title: "No Friends in the Industry", key: 2, bpm: 84),
        Song(id: 452, artist: "Future", title: "I Serve the Base", key: 8, bpm: 84),
        Song(id: 453, artist: "Future", title: "Freak Hoe", key: 12, bpm: 84),
        Song(id: 454, artist: "Cardi B", title: "Up", key: 9, bpm: 84),
        Song(id: 455, artist: "Future", title: "For a Nut", key: 5, bpm: 84),
        Song(id: 456, artist: "Megan thee Stallion", title: "Captain Hook", key: 6, bpm: 84),
        Song(id: 457, artist: "SR3MM", title: "T'd Up", key: 5, bpm: 84),
        Song(id: 458, artist: "Drake", title: "Nonstop", key: 11, bpm: 84),
        Song(id: 459, artist: "Future", title: "I'm on One", key: 2, bpm: 84),
        Song(id: 460, artist: "Drake", title: "Gods Plan", key: 1, bpm: 84),
        Song(id: 461, artist: "Li Uzi Vert", title: "XO TOUR LIFE", key: 1, bpm: 84),
        Song(id: 462, artist: "Mr Bigg", title: "Hos", key: 7, bpm: 84),
        Song(id: 463, artist: "Dem Franchize Boys", title: "I Think They Like Me", key: 5, bpm: 84),
        Song(id: 464, artist: "Sexy Redd", title: "Pound Town", key: 1, bpm: 94),
        Song(id: 465, artist: "Ghostface600", title: "Pray to the East", key: 9, bpm: 94),
        Song(id: 468, artist: "Rick Ross & Meek Mill", title: "Lyrical Eazy", key: 5, bpm: 94),
        Song(id: 469, artist: "Gucci Mane", title: "There I Go", key: 12, bpm: 94),
        Song(id: 474, artist: "Too Short", title: "Young Thang", key: 4, bpm: 94),
        Song(id: 476, artist: "2rare", title: "Lil Mama", key: 1, bpm: 94),
        Song(id: 478, artist: "The Game", title: "Violence", key: 8, bpm: 94),
        Song(id: 485, artist: "10 KANs", title: "D In Your Life", key: 9, bpm: 102),
        Song(id: 486, artist: "2Pac", title: "Still Ballin", key: 2, bpm: 102),
        Song(id: 487, artist: "Das EFX", title: "They Want EFX", key: 1, bpm: 102),
        Song(id: 488, artist: "Kurupt", title: "We Can Freak It", key: 12, bpm: 102),
        Song(id: 489, artist: "Wale", title: "Chillin", key: 1, bpm: 102),
        Song(id: 492, artist: "Derek B", title: "Good Groove", key: 5, bpm: 102),
        Song(id: 493, artist: "50 Cent", title: "Disco Inferno", key: 1, bpm: 102),
        Song(id: 496, artist: "LL Cool J", title: "Eat Em Up L Chill Remix", key: 1, bpm: 102),
        Song(id: 497, artist: "Fabolous", title: "Baby Don't Go", key: 1, bpm: 102),
        Song(id: 498, artist: "Diggy feat French Montana", title: "Ain't Bout to Do", key: 11, bpm: 102),
        Song(id: 499, artist: "DJ Khaled Lil Baby & Future", title: "SUPPOSED TO BE LOVED", key: 1, bpm: 102),
        Song(id: 500, artist: "Pusha T", title: "Let the Smokers Shine the Coupes", key: 5, bpm: 102),
        Song(id: 511, artist: "Blueface", title: "Thotiana", key: 1, bpm: 102),
        Song(id: 512, artist: "Black Sheep", title: "The Choice is Yours", key: 3, bpm: 102),
        Song(id: 513, artist: "Shakira", title: "Hips Don't Lie", key: 3, bpm: 102),
        Song(id: 514, artist: "Beastie Boys", title: "AWOL", key: 1, bpm: 102),
        Song(id: 515, artist: "Ray J", title: "Wait a Minute", key: 1, bpm: 102),
        Song(id: 516, artist: "Frankie Cutlass", title: "Puerto Rico", key: 10, bpm: 102),
        Song(id: 517, artist: "T.I.", title: "Bring Em Out", key: 9, bpm: 102),
        Song(id: 520, artist: "Notorious BIG", title: "Mo Money Mo Problems", key: 1, bpm: 102),
        Song(id: 521, artist: "Showbiz & AG", title: "Party Groove", key: 10, bpm: 102),
        Song(id: 522, artist: "Mario", title: "Boom Remix", key: 1, bpm: 102),
        Song(id: 523, artist: "Positive K", title: "I Got a Man", key: 5, bpm: 102),
        Song(id: 524, artist: "Busta Rhymes", title: "What It Is", key: 4, bpm: 102),
        Song(id: 526, artist: "Kilo", title: "Get In Line 2", key: 3, bpm: 102),
        Song(id: 604, artist: "Lola Brooke", title: "Here I Come", key: 3, bpm: 94),
        Song(id: 605, artist: "Glorilla", title: "Tomorrow 2", key: 8, bpm: 94),
        Song(id: 606, artist: "GloRilla", title: "FNF", key: 5, bpm: 94),
        Song(id: 607, artist: "Cardi B", title: "Bodak Yellow", key: 5, bpm: 94),
        Song(id: 608, artist: "Nicki Minaj", title: "Super Bass", key: 7, bpm: 94),
        Song(id: 609, artist: "Ice Spice", title: "Munch", key: 3, bpm: 94),
        Song(id: 610, artist: "Ice Spice", title: "In Ha Mood", key: 10, bpm: 94),
        Song(id: 611, artist: "Cardi B", title: "WAP", key: 6, bpm: 94),
        Song(id: 614, artist: "Nicki Minaj", title: "Anaconda", key: 2, bpm: 94),
        Song(id: 615, artist: "City Girls", title: "Act Up", key: 5, bpm: 94),
        Song(id: 619, artist: "Doechii", title: "Nissan Altima", key: 5, bpm: 94),
        Song(id: 620, artist: "Trina", title: "Pull Over", key: 4, bpm: 94),
        Song(id: 621, artist: "Lola Brooke", title: "Dummy Ummy", key: 11, bpm: 94),
    ]
}
